//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSyncGui.Ref {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ref.IFileSyncModel")]
    public interface IFileSyncModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/TestWCF", ReplyAction="http://tempuri.org/IFileSyncModel/TestWCFResponse")]
        bool TestWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/TestEF", ReplyAction="http://tempuri.org/IFileSyncModel/TestEFResponse")]
        bool TestEF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/AddUser", ReplyAction="http://tempuri.org/IFileSyncModel/AddUserResponse")]
        bool AddUser(FileSyncObjects.UserContents u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/Login", ReplyAction="http://tempuri.org/IFileSyncModel/LoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool Login(FileSyncObjects.Credentials c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/GetUser", ReplyAction="http://tempuri.org/IFileSyncModel/GetUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        FileSyncObjects.UserIdentity GetUser(FileSyncObjects.Credentials c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/GetUserWithMachines", ReplyAction="http://tempuri.org/IFileSyncModel/GetUserWithMachinesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        FileSyncObjects.UserContents GetUserWithMachines(FileSyncObjects.Credentials c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/DelUser", ReplyAction="http://tempuri.org/IFileSyncModel/DelUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool DelUser(FileSyncObjects.Credentials c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/AddMachine", ReplyAction="http://tempuri.org/IFileSyncModel/AddMachineResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool AddMachine(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/ChangeMachineDetails", ReplyAction="http://tempuri.org/IFileSyncModel/ChangeMachineDetailsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool ChangeMachineDetails(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents newM, FileSyncObjects.MachineContents oldM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/GetMachineWithDirs", ReplyAction="http://tempuri.org/IFileSyncModel/GetMachineWithDirsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.MachineContents))]
        FileSyncObjects.MachineContents GetMachineWithDirs(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/DelMachine", ReplyAction="http://tempuri.org/IFileSyncModel/DelMachineResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.MachineContents))]
        bool DelMachine(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/AddDirectory", ReplyAction="http://tempuri.org/IFileSyncModel/AddDirectoryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool AddDirectory(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/GetDirectoryWithFiles", ReplyAction="http://tempuri.org/IFileSyncModel/GetDirectoryWithFilesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.DirectoryContents))]
        FileSyncObjects.DirectoryContents GetDirectoryWithFiles(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryIdentity d);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/DelDirectory", ReplyAction="http://tempuri.org/IFileSyncModel/DelDirectoryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.MachineContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.DirectoryContents))]
        bool DelDirectory(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid, FileSyncObjects.DirectoryIdentity did);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/AddFile", ReplyAction="http://tempuri.org/IFileSyncModel/AddFileResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        bool AddFile(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d, FileSyncObjects.FileContents f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/GetFileWithContent", ReplyAction="http://tempuri.org/IFileSyncModel/GetFileWithContentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.FileContents))]
        FileSyncObjects.FileContents GetFileWithContent(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d, FileSyncObjects.FileIdentity f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSyncModel/DelFile", ReplyAction="http://tempuri.org/IFileSyncModel/DelFileResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.UserContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.MachineContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.DirectoryContents))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileSyncObjects.FileContents))]
        bool DelFile(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid, FileSyncObjects.DirectoryIdentity did, FileSyncObjects.FileIdentity f);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileSyncModelChannel : FileSyncGui.Ref.IFileSyncModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSyncModelClient : System.ServiceModel.ClientBase<FileSyncGui.Ref.IFileSyncModel>, FileSyncGui.Ref.IFileSyncModel {
        
        public FileSyncModelClient() {
        }
        
        public FileSyncModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSyncModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSyncModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSyncModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestWCF() {
            return base.Channel.TestWCF();
        }
        
        public bool TestEF() {
            return base.Channel.TestEF();
        }
        
        public bool AddUser(FileSyncObjects.UserContents u) {
            return base.Channel.AddUser(u);
        }
        
        public bool Login(FileSyncObjects.Credentials c) {
            return base.Channel.Login(c);
        }
        
        public FileSyncObjects.UserIdentity GetUser(FileSyncObjects.Credentials c) {
            return base.Channel.GetUser(c);
        }
        
        public FileSyncObjects.UserContents GetUserWithMachines(FileSyncObjects.Credentials c) {
            return base.Channel.GetUserWithMachines(c);
        }
        
        public bool DelUser(FileSyncObjects.Credentials c) {
            return base.Channel.DelUser(c);
        }
        
        public bool AddMachine(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m) {
            return base.Channel.AddMachine(c, m);
        }
        
        public bool ChangeMachineDetails(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents newM, FileSyncObjects.MachineContents oldM) {
            return base.Channel.ChangeMachineDetails(c, newM, oldM);
        }
        
        public FileSyncObjects.MachineContents GetMachineWithDirs(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid) {
            return base.Channel.GetMachineWithDirs(c, mid);
        }
        
        public bool DelMachine(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid) {
            return base.Channel.DelMachine(c, mid);
        }
        
        public bool AddDirectory(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d) {
            return base.Channel.AddDirectory(c, m, d);
        }
        
        public FileSyncObjects.DirectoryContents GetDirectoryWithFiles(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryIdentity d) {
            return base.Channel.GetDirectoryWithFiles(c, m, d);
        }
        
        public bool DelDirectory(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid, FileSyncObjects.DirectoryIdentity did) {
            return base.Channel.DelDirectory(c, mid, did);
        }
        
        public bool AddFile(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d, FileSyncObjects.FileContents f) {
            return base.Channel.AddFile(c, m, d, f);
        }
        
        public FileSyncObjects.FileContents GetFileWithContent(FileSyncObjects.Credentials c, FileSyncObjects.MachineContents m, FileSyncObjects.DirectoryContents d, FileSyncObjects.FileIdentity f) {
            return base.Channel.GetFileWithContent(c, m, d, f);
        }
        
        public bool DelFile(FileSyncObjects.Credentials c, FileSyncObjects.MachineIdentity mid, FileSyncObjects.DirectoryIdentity did, FileSyncObjects.FileIdentity f) {
            return base.Channel.DelFile(c, mid, did, f);
        }
    }
}
